### ISSUE TITLE
base64 encoded email -> plaintext issues

### ISSUE THREAD

**Issue by ouija** [aymanrb/php-unstructured-text-parser#19]
Hey,

Not sure if you can assist with this but figured I'd post an issue in case you have some insight.

I've been using this **awesome** library for some time _[thanks!]_ but recently ran into some issues with a client that was sending emails encoded in base64 format, and having an issue matching the decoded (plaintext) message to any templates.

I've never had to decode base64 encoded emails until recently, and discovered that simply using `imap_base64` wasn't working in terms of getting them to plaintext, and that the decoded message was in HTML format.

So I've attempted to make use of the [html2text](https://github.com/soundasleep/html2text) library in order to convert the decoded base64 messages and remove the HTML formatting, however, the php-unstructured-text-parser doesn't seem to be matching any of the data defined within the template when running it against a data variable that contains the plaintext data formatted by html2text.

However, if I parse an actual email composed with the body of the data created/formatted by this html2text library, it **does** work..  so I'm somewhat left scratching my head here as to why it won't work when comparing against this same data [stored in a variable].

I'm thinking of just shooting another email out into the queue for parsing (composed of the data generated by html2text) and re-parsing it that way, but this isn't ideal and if you have any suggestions on where I can improve this (or improvements to what I've descibed), let me know!

Also note that I'm using `dev-master` branch of the library with my application, since I too was having [similar issues](https://github.com/aymanrb/php-unstructured-text-parser/issues/17) parsing plaintext emails and having linebreaks ignored in my templates.

Thanks!

**Comment by aymanrb** [comment]
hey @ouija,

Thank you for using the library, trying the unreleased changes and asking the question here. The different use cases helps enhance the code to cover more options.

To start with I would personally avoid the workaround you suggested for now (sending another email to the queue). This is an overhead with new potential points of failure we can hopefully avoid.

The use case you described (parsing HTML mail content) was the main reason I wrote this library, in my case I still create the template out of the whole decoded HTML body and replace the variable text directly in the HTML. Yet I guess converting it to plain text like you did is smart and should hopefully be easier.

Since what you see is not always what you get, I would try to create a base template file from the converted text (not by copying it but rather storing it from the variable directly).

```
$plainTxt = Html2Text::convert($htmlBody);
file_put_contents('pathToTemplateFile.txt', $plainTxt);
```

Then change the variable text (reduce the amount of variable at the beginning, try with replacing one variable only and leave everything else in the text as it is, i.e. not parsed by the template yet).

So in general this should be the easiest way to start with:
1- Save the text exactly as you get it from the variable, not as you see it
2- Replace one variable after the other testing it against the same text always until you are done with the whole template before trying it on a different email with the same structure.

Give this a try and let me know how it went, I would be happy to assist you get this done / fixed.

**Comment by ouija** [comment]
Hey,

Apologies for the super late follow up to this, but finally had some time to debug this today.

I'm still having issues when it comes to emails encoding in BASE64 MULTIPART/ALTERNATIVE format, and the `$parser->parseText($message)->getParsedRawData()` method returning empty or not matching anything in the templates, unless I actually send this data again as another message to be parsed.

I can't explain it.   I did exactly as you instructed and saved the decoded BASE64 variable to a text file and checked it against my template, but it comes out EXACTLY the same as what I have, but it returns empty/doesn't match any data.   But if I take that exact same variable of data and send it as a separate email and parse against that, then it works.

It's something to do with this client and the system they are using to generate these emails.  It's almost as if the body of the emails is the same data as the PDF they are generating at the same time (and attaching to these emails that I'm parsing data for).


Just for reference, here's the function I'm using to decode certain messages via php imap:

```
// Email Decoding Function
function decodeEmail($encoding, $text, $decode) {
	switch ($encoding) {
		# 7BIT
		case 0:
			if (!$decode) return "7BIT";
			else return $text;
		# 8BIT
		case 1:
			if (!$decode) return "8BIT";
			else return quoted_printable_decode(imap_8bit($text));
		# BINARY
		case 2:
			if (!$decode) return "BINARY";
			else return imap_binary($text);
		# BASE64
		case 3:
			if (!$decode) return "BASE64";
			// imap_base64($text) decodes in HTML formatted email, converting to plain text via html2text
			else return \Soundasleep\Html2Text::convert(imap_base64($text),array(
			  'ignore_errors' => true,
			  'drop_links' => true
			));
		# QUOTED-PRINTABLE
		case 4:
			if (!$decode) return "QUOTED-PRINTABLE";
			else return quoted_printable_decode($text);
		# OTHER
		case 5:
			if (!$decode) return "OTHER";
			else return $text;
		# UNKNOWN
		default:
			if (!$decode) return "UNKNOWN";
			else return $text;
	}
}
```

The strange thing is if an email is BASE64 and the body is decoded using this function and parsed, it won't match the templates, but if you resend that very same decoded data as a second email, then it will match the templates (and the data is exactly the same, no difference) so I'm not sure if it's a conflict between how this Html2Text stores data to the variable and how the parser reads it or what.... I'm baffled on this one..

**Comment by aymanrb** [comment]
I am sorry for not being able to help here, the issue is bit confusing unless I get access to debug it myself I might find a different path.

I would still personally ignore the template I have for now and create a new one out of the the file you saved from the email. So you said you saved the variable into a file and ran it against "your template", I would actually copy the file as it is (duplicate it) and make it the template, then replace only one variable at a time and run a test against the original message until all variables in the message(s) are replaced by parser variables.

I know what I am saying sounds stupid, since you can verify already that what you have in the file "looks" like your template, but I wouldn't trust that and start debugging from an earlier point. If your template and parsed file are the exact same source, I am confident enough it will yield some results.

**Comment by ouija** [comment]
I just realized you still had this issue open;  For now, a workaround I came up with was to simply resend emails back into the account when this issue was encountered, and it's been making due for the time being.
