### ISSUE TITLE
Advice on handling Complex Extract Template 

### ISSUE THREAD

**Issue by ssmusoke** [aymanrb/php-unstructured-text-parser#20]
Hello,

I have gotten the following text (12345678 John Anthony Doe) with the names being able to vary, I have tried the template ({%id%} {%name%}) however I end up with the values 12345678 John Anthony and Doe

Do you have any advice on how I can code the template to take the number alone and the rest of the text string?

Thank you in advance

**Comment by aymanrb** [comment]
Well, unfortunately with the current version of the parser this will not work. The template variables are dumb at its current state and it tries to match any character within the scope of the variable using a broad regex  (.*) 

Reference: src/Helper/TemplateHelper::prepareTemplate()

What you are trying to do is a very valid usecase though (wasn't needed in the projects I used the parser in though so it wasn't implemented)

There should be a way to make the variables bit smarter and be let it dictate the expected data type and/or characters set to match.

I am unfortunately away from my laptop for at least 10 more days and won't be able to implement it but will consider it in the next release because it makes total sense and will make the parser a bit more powerful.

**Comment by ssmusoke** [comment]
Thank you for the quick response, first of all please do enjoy your time off I am sure it is well deserved 

I will figure something out on how to do it and will share whatever I do work out with. Your project is such a life saver and works so seamlessly - basically it has been a Godsend to me

**Comment by aymanrb** [comment]
Thanks for those kind words.

So basically what we want to achieve is some sort of regex associated with the variable with a  fallback to the generic ".*" match in case nothing specific was provided by the variable. I would personally prefer this to be with the variable in the template (for maintainability and readability) but it could also be implemented in some sort of a config file outside the template, which doesn't seem feasible to me given the current usecases.

So a variable could either be just a name like we have now:
{%id%} {%name%}

Or a name with regex to match like:
{%id:^[0-9]%} {%name:^[a-z ,.'-]+$%}

We will then have to modify the template preparation process to handle that.

What do you think about it? Feel free to share your thoughts / attempts (if any) with me anytime.

**Comment by aymanrb** [comment]
Hi @ssmusoke 

I finally got the time to look into this. Could you please check if **[this](https://github.com/aymanrb/php-unstructured-text-parser/pull/21)** works for your usecase and let me know if you see any improvements / issues with it.

Thanks :slightly_smiling_face:
